---
spring:
  profiles: cloud
application:
  domain: 23.23.221.131.xip.io
eureka:
  instance:
    hostname: ${spring.application.name}.${application.domain:cfapps.io}
    nonSecurePort: 80
service:
  definition:
    metadata:
      uri: http://${spring.application.name}.${application.domain:cfapps.io}