---
application:
  domain: 23.23.221.131.xip.io
spring:
  profiles: cloud
  platform:
    config:
      uri: ${vcap.services.configserver.credentials.uri}
eureka:
  instance:
    hostname: ${spring.application.name}.${application.domain:cfapps.io}
    nonSecurePort: 80
