info:
  new:
  stuff: Hello World

---
spring:
  profiles: cloud
  platform:
    config:
      uri: ${vcap.services.configserver.credentials.uri:http://${configserver.${application.domain:cfapps.io}}}
application:
  domain: 184.72.224.23.xip.io
endpoints:
  restart: enabled
cloudfoundry:
  service:
    definition:
      metadata:
        uri: http://${spring.application.name}.${application.domain:cfapps.io}
eureka:
  instance:
    hostname: ${spring.application.name}.${application.domain:cfapps.io}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka.credentials.uri:http://eureka.${application.domain:cfapps.io}/}v2/
      default.defaultZone: ${vcap.services.eureka.credentials.uri:http://eureka.${application.domain:cfapps.io}/}v2/
