AppSettings:
  MaxPost: 20
KafkaSettings:
  Ips : 172.20.0.3:9092
  FacebookWebListenerTopic: fbpoll

eureka:
  client:
    serviceUrl: http://172.20.0.7:8761/eureka/
    validate_certificates: false
spring:
  cloud:
    config:
       server:
         uri: "http://172.20.0.8:8888"
         